# Configuration for python-semantic-release
[tool.semantic_release]
version_variable = ["pyproject.toml:version"]
branch = "main"
commit_author = "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
changelog_file = "CHANGELOG.md"

[tool.semantic_release.changelog]
exclude_commit_patterns = ["chore(release):*"]
