services:
  daily-flavors-app:
    build: .
    ports:
      - 8080:80
    develop:
      watch: 
        - action: sync+restart
          path: ./app
          target: /code/app
        - action: sync+restart
          path: ./static
          target: /code/static
