[tool.black]
line-length = 100
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 100

[tool.flake8]
ignore = "E501" # Ignore long lines, handled by Black 
exclude = ".git,__pycache__,.venv,venv,build,dist"

[tool.pytest.ini_options]
pythonpath = ["app"]

[tool.coverage.run]
branch = true
source = ["app"]

[tool.coverage.report]
omit = [
    "tests/*",
    "__init__.py"
]
show_missing = true

[tool.pip-audit]
ignore-vulns = []
