name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  packages: write

jobs:
  test:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -e .[dev]
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Lint with flake8
        run: flake8 app tests
      - name: Check formatting with black
        run: black --check app tests
      - name: Check import sorting with isort
        run: isort --check-only app tests
      - name: Run tests with coverage
        run: pytest --cov=app --cov-report=term-missing
      - name: Security audit with pip-audit
        run: pip-audit
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/daily-flavors-app:latest .
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/daily-flavors-app:latest
