name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (optional, semantic-release will determine if omitted)'
        required: false

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Ecosystem tests
        run: |
          pytest --ecosystem --log-level=DEBUG --log-file=ecosystem_test.log
      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ecosystem-test-log
          path: ecosystem_test.log
      - name: Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: false
      - name: Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v10.2.0
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
      
      - name: Notify on release success
        if: success()
        run: |
          curl -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
               -H "Title: Daily Flavors App Release Job Completed" \
               -H "Priority: normal" \
               -d "The daily flavors app release job has completed successfully. Version: ${{ steps.release.outputs.version }}" \
               ${{ secrets.NTFY_TOPIC_URL }}
      
      - name: Notify on release failure
        if: failure()
        run: |
          curl -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN}}" \
               -H "Title: Daily Flavors App Release Job Failed" \
               -H "Priority: high" \
               -d "The daily flavors app release job has failed. Check the workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
               ${{ secrets.NTFY_TOPIC_URL }}

  publish_docker:
    if: ${{ needs.release.outputs.released == 'true' }}
    runs-on: ubuntu-latest
    needs: release
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/daily-flavors-app:${{ needs.release.outputs.version }} -t ghcr.io/${{ github.repository_owner }}/daily-flavors-app:latest .
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/daily-flavors-app:${{ needs.release.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/daily-flavors-app:latest
      
      - name: Notify on docker success
        if: success()
        run: |
          curl -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
               -H "Title: Daily Flavors App Docker Published" \
               -H "Priority: normal" \
               -d "The daily flavors app Docker image has been published successfully. Version: ${{ needs.release.outputs.version }}. Check it out: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ needs.release.outputs.tag }}" \
               ${{ secrets.NTFY_TOPIC_URL }}
      
      - name: Notify on docker failure
        if: failure()
        run: |
          curl -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN}}" \
               -H "Title: Daily Flavors App Docker Publish Failed" \
               -H "Priority: high" \
               -d "The daily flavors app Docker publish job has failed. Check the workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
               ${{ secrets.NTFY_TOPIC_URL }}


